import { Inter } from "next/font/google";
import '../Style/globals.css'
import NavBar from "@/pages/NavBar";
import Footer from "@/pages/Footer";
import { UserLogin } from '@/context/UserloginStatus'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserLogin>
           <NavBar />
             <div className='text-white text-center h-screen border-red-200 bg-red-500'>
               {children}
             </div>
           <Footer />
        </UserLogin>
      </body>
    </html>
  );
}
